extern unsigned char learning_example_simple_audio_recognition_application_tflite_model_audio_recognition_model_tflite[];
extern unsigned int learning_example_simple_audio_recognition_application_tflite_model_audio_recognition_model_tflite_len;
