#ifndef AUDIO_MODEL_PIPELINE_H_
#define AUDIO_MODEL_PIPELINE_H_

#include <vector>
#include <cstdint>
#include "tflite_model_handler.h"
#include "common_types.h"

namespace audio_model_pipeline
{
    constexpr size_t INPUT_SAMPLE_COUNT = 16000;
    constexpr size_t SPECTROGRAM_ROWS = 124;
    constexpr size_t SPECTROGRAM_COLS = 129;
    constexpr size_t TOTAL_INPUT_ELEMENTS = SPECTROGRAM_ROWS * SPECTROGRAM_COLS;

    /*
     * @brief Initializes the audio model pipeline by pre-computing necessary coefficients.
     */
    void HannWindowInit(void);

    /**
     * @brief Computes the Short-Time Fourier Transform (STFT) using a Hann Window.
     *        Converts a raw 1D PCM waveform into a flat 2D magnitude spectrogram array.
     *        Normalization to [-1, 1] is applied inside this function.
     *
     * @param raw_waveform The 16000-element raw PCM-scale waveform.
     * @return FeatureFloatVec Flattened spectrogram of size 15996 (124 rows x 129 cols).
     */
    ml_types_dynamic::FeatureFloatVec ComputeSTFT(ml_types_dynamic::RawSignalFloatVec &raw_waveform);

    /**
     * @brief Quantizes a float spectrogram array into an INT8 buffer using
     *        scale and zero-point parameters, then executes model inference.
     *
     * @param engine Pointer to the generic TFLite execution handler.
     * @param float_spectrogram Pre-calculated 1D float spectrogram data vector.
     * @param spectrogram_gain Gain factor to boost spectrogram values before quantization.
     * @return PredictionFloatVec Final classification probabilities generated by the network.
     */
    ml_types_dynamic::PredictionFloatVec RunInference(
        tflite_model_handler::TFLiteModelHandler<10> *engine,
        const ml_types_dynamic::FeatureFloatVec &float_spectrogram, const float spectrogram_gain);
}

#endif // AUDIO_MODEL_PIPELINE_H_
